language: go
go:
  - 1.6
services:
  - postgresql
  - mysql
addons:
  postgresql: "9.4"
before_script:
  - mysql -e 'CREATE DATABASE testfixtures_test;'
  - psql -c 'CREATE DATABASE testfixtures_test;' -U postgres
script: sh test_with_sqlite.sh
