version: '{build}'

clone_folder: C:\GOPATH\src\gopkg.in\testfixtures.v2

build: false
deploy: false

services:
  - postgresql96
  - mysql
  - mssql2017

environment:
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
  PG_CONN_STRING: 'user=postgres password=Password12! dbname=testfixtures_test sslmode=disable'

  MYSQL_PWD: Password12!
  MYSQL_CONN_STRING: 'root:Password12!@/testfixtures_test?multiStatements=true'

  SQLITE_CONN_STRING: 'testdb.sqlite3'

  SQLSERVER_CONN_STRING: 'server=localhost;database=testfixtures_test;user id=sa;password=Password12!;encrypt=disable'

  GOPATH: C:\GOPATH
  GOVERSION: 1.10.2

install:
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%

  - createdb testfixtures_test

  - mysql -e "CREATE DATABASE testfixtures_test;" --user=root

  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE testfixtures_test" -d "master"

  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - go version

test_script:
  - go get -u -t -tags 'sqlite postgresql mysql sqlserver' ./...
  - go get github.com/go-task/task/cmd/task
  - go install -v ./...
  - task test-pg
  - task test-mysql
  - task test-sqlite
  - task test-sqlserver
